const MoviesActionTypes = {
  FETCH_MOVIES: 'FETCH_MOVIES',
  LOADING_MOVIES_LIST: 'LOADING_MOVIES_LIST',
  SET_CURRENT_SEARCH: 'SET_CURRENT_SEARCH',
  SET_MOVIES_LIST: 'SET_MOVIES_LIST',
  HANDLE_FAVORITE_MOVIE: 'HANDLE_FAVORITE_MOVIE',
}

export default MoviesActionTypes
